// HintName: EuterpeApi.Urls.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


namespace Euterpe.Shared;

public static partial class EuterpeApi
{
    public static partial class Account
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.EuterpeApiUrlGenerator", "1.0.0")]
        public const string BaseUrl = EuterpeApi.BaseUrl + BasePath;
    }

    public static partial class Auth
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.EuterpeApiUrlGenerator", "1.0.0")]
        public const string BaseUrl = EuterpeApi.BaseUrl + BasePath;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.EuterpeApiUrlGenerator", "1.0.0")]
        public const string AppTokenUrl = BaseUrl + AppToken;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.EuterpeApiUrlGenerator", "1.0.0")]
        public const string LogoutUrl = BaseUrl + Logout;
    }

    public static partial class Distribution
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.EuterpeApiUrlGenerator", "1.0.0")]
        public const string BaseUrl = EuterpeApi.BaseUrl + BasePath;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.EuterpeApiUrlGenerator", "1.0.0")]
        public const string LibsUrl = BaseUrl + LibsPath;
    }
}
