// HintName: CoreServiceExtensions.PlatformServices.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


namespace Euterpe.Core.Extensions;

public static partial class CoreServiceExtensions
{
    extension(ContainerBuilder builder)
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.PlatformServiceExtensionsGenerator", "1.0.0")]
        private void RegisterPerPlatformAppServices()
        {
            #pragma warning disable CA1416
            #if LINUX
            builder.RegisterType<global::Sample.LinuxLauncher>().As<global::Euterpe.Abstractions.IPlatformLauncher>().PropertiesAutowired().SingleInstance();
            #elif MACOS
            builder.RegisterType<global::Sample.MacOsLauncher>().As<global::Euterpe.Abstractions.IPlatformLauncher>().PropertiesAutowired().SingleInstance();
            #elif WINDOWS
            builder.RegisterType<global::Sample.WindowsLauncher>().As<global::Euterpe.Abstractions.IPlatformLauncher>().PropertiesAutowired().SingleInstance();
            #endif
            #pragma warning restore CA1416
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.PlatformServiceExtensionsGenerator", "1.0.0")]
        private void RegisterPerPlatformGameServices()
        {
            #pragma warning disable CA1416
            #if LINUX
            builder.RegisterType<global::Sample.LinuxGamePathDiscovery>().As<global::Euterpe.Abstractions.IGamePathDiscovery>().PropertiesAutowired().InstancePerLifetimeScope();
            #elif MACOS
            builder.RegisterType<global::Sample.MacOsGamePathDiscovery>().As<global::Euterpe.Abstractions.IGamePathDiscovery>().PropertiesAutowired().InstancePerLifetimeScope();
            #elif WINDOWS
            builder.RegisterType<global::Sample.WindowsGamePathDiscovery>().As<global::Euterpe.Abstractions.IGamePathDiscovery>().PropertiesAutowired().InstancePerLifetimeScope();
            #endif
            #pragma warning restore CA1416
        }
    }
}
