// HintName: SettingsViewModel.Routes.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System.Collections.Frozen;

namespace Sample;

partial class SettingsViewModel
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    public override global::System.Collections.Generic.IReadOnlyList<global::Euterpe.Controls.Models.NavItem> NavItems { get; } =
    [
        new(global::Euterpe.Localization.XAMLLiteral.General, "/settings/general"),
        new(global::Euterpe.Localization.XAMLLiteral.Advanced, "/settings/advanced"),
    ];

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    private static readonly FrozenDictionary<string, global::System.Func<global::Autofac.IComponentContext, global::Euterpe.Mvvm.ViewModelBase>> RouteLookup = new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::Autofac.IComponentContext, global::Euterpe.Mvvm.ViewModelBase>>
    {
        ["/settings/general"] = static ctx => ctx.Resolve<global::Sample.GeneralViewModel>(),
        ["/settings/advanced"] = static _ => global::Euterpe.IocContainer.Resolve<global::Sample.AdvancedViewModel>(),
    }.ToFrozenDictionary();

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    protected override global::Euterpe.Mvvm.ViewModelBase ResolveRoute(string route) => RouteLookup[route](Container);
}
