// HintName: RouteTree.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using static Euterpe.IocContainer;

namespace Euterpe;

public static class RouteTree
{
    public static readonly global::Euterpe.Controls.Models.RouteNode Root = new("/", null, [
        new("/home", () => { var vm = Resolve<global::Sample.RootViewModel>(); vm.SelectedItem = vm.NavItems[0]; }, []),
        new("/settings", () => { var vm = Resolve<global::Sample.RootViewModel>(); vm.SelectedItem = vm.NavItems[1]; }, [
            new("/settings/general", () => { var vm = Resolve<global::Sample.SettingsViewModel>(); vm.SelectedItem = vm.NavItems[0]; }, []),
            new("/settings/advanced", () => { var vm = Resolve<global::Sample.SettingsViewModel>(); vm.SelectedItem = vm.NavItems[1]; }, []),
        ]),
    ]);
}
