// HintName: RootViewModel.Routes.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System.Collections.Frozen;

namespace Sample;

partial class RootViewModel
{
    public global::Euterpe.Mvvm.PageHost HomeHost { get; } = global::Euterpe.Mvvm.PageHost.PerGame<global::Sample.HomeViewModel>();
    public global::Euterpe.Mvvm.PageHost SettingsHost { get; } = global::Euterpe.Mvvm.PageHost.App(global::Euterpe.IocContainer.Resolve<global::Sample.SettingsViewModel>());

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    public override global::System.Collections.Generic.IReadOnlyList<global::Euterpe.Controls.Models.NavItem> NavItems { get; } =
    [
        new(global::Euterpe.Localization.XAMLLiteral.Home, "/home") { IconResourceKey = "house" },
        new(global::Euterpe.Localization.XAMLLiteral.Settings, "/settings") { IconResourceKey = "gear" },
    ];

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    public override global::System.Collections.Generic.IReadOnlyList<global::Euterpe.Mvvm.PageHost> Pages => field ??= [HomeHost, SettingsHost];

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    private static readonly FrozenDictionary<string, int> RouteIndex = new global::System.Collections.Generic.Dictionary<string, int>
    {
        ["/home"] = 0,
        ["/settings"] = 1,
    }.ToFrozenDictionary();

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    protected override global::Euterpe.Mvvm.PageHost ResolveRoute(string route) => Pages[RouteIndex[route]];
}
