// HintName: ServiceExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


namespace Euterpe.Extensions;

partial class ServiceExtensions
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.ServiceExtensionsGenerator", "1.0.0")]
    public static void RegisterAppViewModels(this ContainerBuilder builder)
    {
        builder.RegisterType<global::Sample.CrashViewModel>().PropertiesAutowired().SingleInstance();
        builder.RegisterType<global::Sample.HomeViewModel>().PropertiesAutowired().SingleInstance();
        builder.RegisterType<global::Sample.RootViewModel>().PropertiesAutowired().SingleInstance();
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.ServiceExtensionsGenerator", "1.0.0")]
    public static void RegisterPerGameViewModels(this ContainerBuilder builder)
    {
        builder.RegisterType<global::Sample.ModdingViewModel>().PropertiesAutowired().InstancePerLifetimeScope();
        builder.RegisterType<global::Sample.WizardDialogViewModel>().PropertiesAutowired().InstancePerLifetimeScope();
    }
}
